/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihan11.newpackage;

/**
 *
 * @author isalr
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Matematika
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbJudul = new javax.swing.JLabel();
        LbAngka1 = new javax.swing.JLabel();
        LbAngka2 = new javax.swing.JLabel();
        Txt_Bil1 = new javax.swing.JTextField();
        Txt_Bil2 = new javax.swing.JTextField();
        Btn_Tambah = new javax.swing.JButton();
        Btn_Kurang = new javax.swing.JButton();
        Btn_Bagi = new javax.swing.JButton();
        Btn_Kali = new javax.swing.JButton();
        LbHasil = new javax.swing.JLabel();
        LblNilai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LbJudul.setText("KALKULATOR");

        LbAngka1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbAngka1.setText("Angka Pertama");

        LbAngka2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbAngka2.setText("Angka Kedua");

        Txt_Bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Bil2ActionPerformed(evt);
            }
        });

        Btn_Tambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Tambah.setText("+");
        Btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TambahActionPerformed(evt);
            }
        });

        Btn_Kurang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Kurang.setText("-");
        Btn_Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KurangActionPerformed(evt);
            }
        });

        Btn_Bagi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Bagi.setText("/");
        Btn_Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BagiActionPerformed(evt);
            }
        });

        Btn_Kali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Kali.setText("X");
        Btn_Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KaliActionPerformed(evt);
            }
        });

        LbHasil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHasil.setText("Hasil    =");

        LblNilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNilai.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LbAngka2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbAngka1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_Bil1)
                                    .addComponent(Txt_Bil2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblNilai)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(Btn_Bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Kali, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LbJudul)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LbJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAngka1)
                    .addComponent(Txt_Bil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAngka2)
                    .addComponent(Txt_Bil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Tambah)
                    .addComponent(Btn_Kurang)
                    .addComponent(Btn_Bagi)
                    .addComponent(Btn_Kali))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbHasil)
                    .addComponent(LblNilai))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BagiActionPerformed
        // TODO add your handling code here:
        float jumlah, bil1, bil2;
        bil1 = Integer.valueOf(Txt_Bil1.getText());
        bil2 = Integer.valueOf(Txt_Bil2.getText());
        jumlah = bil1/bil2;
        LblNilai.setText(""+jumlah);
    }//GEN-LAST:event_Btn_BagiActionPerformed

    private void Txt_Bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Bil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Bil2ActionPerformed

    private void Btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahActionPerformed
        // TODO add your handling code here:
        int jumlah, bil1, bil2;
        bil1 = Integer.valueOf(Txt_Bil1.getText());
        bil2 = Integer.valueOf(Txt_Bil2.getText());
        jumlah = bil1+bil2;
        LblNilai.setText(""+jumlah);
    }//GEN-LAST:event_Btn_TambahActionPerformed

    private void Btn_KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KurangActionPerformed
        // TODO add your handling code here:
        int jumlah, bil1, bil2;
        bil1 = Integer.valueOf(Txt_Bil1.getText());
        bil2 = Integer.valueOf(Txt_Bil2.getText());
        jumlah = bil1 - bil2;
        LblNilai.setText(""+jumlah);
    }//GEN-LAST:event_Btn_KurangActionPerformed

    private void Btn_KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KaliActionPerformed
        // TODO add your handling code here:
        int jumlah, bil1, bil2;
        bil1 = Integer.valueOf(Txt_Bil1.getText());
        bil2 = Integer.valueOf(Txt_Bil2.getText());
        jumlah = bil1*bil2;
        LblNilai.setText(""+jumlah);
    }//GEN-LAST:event_Btn_KaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Bagi;
    private javax.swing.JButton Btn_Kali;
    private javax.swing.JButton Btn_Kurang;
    private javax.swing.JButton Btn_Tambah;
    private javax.swing.JLabel LbAngka1;
    private javax.swing.JLabel LbAngka2;
    private javax.swing.JLabel LbHasil;
    private javax.swing.JLabel LbJudul;
    private javax.swing.JLabel LblNilai;
    private javax.swing.JTextField Txt_Bil1;
    private javax.swing.JTextField Txt_Bil2;
    // End of variables declaration//GEN-END:variables
}
